# Generated by Django 3.2.23 on 2023-11-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('resourceId', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('traceId', models.CharField(max_length=255)),
                ('spanId', models.CharField(max_length=255)),
                ('commit', models.CharField(max_length=255)),
                ('metadata', models.JSONField(max_length=255)),
            ],
        ),
    ]
